// node scripts/build-cea608.cjs [path-to-typescript-package]
// Transpile the pinned parser; no player or network dependencies are bundled.
const fs = require('node:fs');
const path = require('node:path');
const ts = require(process.argv[2] || 'typescript');
const root = path.join(__dirname, '..');
const source = fs.readFileSync(path.join(root, 'browser/cea608/cea-608-parser.ts'), 'utf8')
  .replace("import { stringify } from './safe-json-stringify';", 'const stringify = JSON.stringify;')
  .replace("import { logger } from '../utils/logger';", 'const logger = { log() {} };');
const result = ts.transpileModule(source, { compilerOptions: {
  target: ts.ScriptTarget.ES2020, module: ts.ModuleKind.ES2020, removeComments: false,
} });
fs.writeFileSync(path.join(root, 'src/ui/mv-cea608.mjs'), '// Generated by scripts/build-cea608.cjs; see browser/cea608.\n' + result.outputText);
